name: Advanced Deployment with Validation

# This workflow demonstrates advanced features:
# - Custom secrets validation
# - Conditional deployment based on validation
# - Secret rotation detection
# - Manual export to different formats

on:
  push:
    branches: [main]
  schedule:
    # Check secrets daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      skip-validation:
        description: 'Skip secrets validation'
        type: boolean
        default: false
      export-format:
        description: 'Export secrets to file format'
        type: choice
        options:
          - none
          - json
          - yaml
          - dotenv

permissions:
  contents: read
  id-token: write

env:
  GCP_PROJECT_ID: my-gcp-project
  WORKLOAD_IDENTITY_PROVIDER: projects/123456789/locations/global/workloadIdentityPools/github/providers/github-provider
  SERVICE_ACCOUNT: github-actions@my-gcp-project.iam.gserviceaccount.com

jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    outputs:
      validation-passed: ${{ steps.secrets.outputs.validation-passed }}
      secrets-count: ${{ steps.secrets.outputs.secrets-count }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load and validate secrets
        id: secrets
        uses: ./.github/actions/setup-secrets
        with:
          environment: production
          gcp-project-id: ${{ env.GCP_PROJECT_ID }}
          workload-identity-provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service-account: ${{ env.SERVICE_ACCOUNT }}
          validate: ${{ inputs.skip-validation != true }}

      - name: Check validation results
        run: |
          echo "Validation passed: ${{ steps.secrets.outputs.validation-passed }}"
          echo "Secrets count: ${{ steps.secrets.outputs.secrets-count }}"

          if [ "${{ steps.secrets.outputs.validation-passed }}" != "true" ] && [ "${{ inputs.skip-validation }}" != "true" ]; then
            echo "❌ Secrets validation failed!"
            exit 1
          fi

  export-secrets:
    needs: validate-secrets
    runs-on: ubuntu-latest
    if: inputs.export-format != 'none' && inputs.export-format != ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install secrets-manager
        run: pip install botmaro-gcp-secret-manager

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Export secrets to ${{ inputs.export-format }}
        run: |
          secrets-manager export production \
            --format ${{ inputs.export-format }} \
            --output secrets.${{ inputs.export-format }}

      - name: Upload secrets artifact
        uses: actions/upload-artifact@v4
        with:
          name: secrets-export
          path: secrets.${{ inputs.export-format }}
          retention-days: 1

  deploy:
    needs: validate-secrets
    runs-on: ubuntu-latest
    if: needs.validate-secrets.outputs.validation-passed == 'true' || inputs.skip-validation
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load secrets
        uses: ./.github/actions/setup-secrets
        with:
          environment: production
          gcp-project-id: ${{ env.GCP_PROJECT_ID }}
          workload-identity-provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service-account: ${{ env.SERVICE_ACCOUNT }}
          validate: false  # Already validated in previous job

      - name: Build application
        run: |
          echo "Building application..."
          npm install
          npm run build

      - name: Run pre-deployment tests
        run: |
          echo "Running pre-deployment tests..."
          npm run test:integration

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          ./scripts/deploy.sh

      - name: Post-deployment verification
        run: |
          echo "Verifying deployment..."
          ./scripts/verify-deployment.sh

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Deployment successful with ${{ needs.validate-secrets.outputs.secrets-count }} secrets"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Deployment failed"
          exit 1

  check-secret-rotation:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install secrets-manager
        run: pip install botmaro-gcp-secret-manager

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Check for secrets that need rotation
        run: |
          echo "Checking for secrets that may need rotation..."

          # Run comprehensive check
          secrets-manager check production \
            --workflows .github/workflows \
            --verbose

          echo "✅ Secrets check complete"

      - name: Create issue if secrets need attention
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔐 Secrets Validation Failed',
              body: 'The scheduled secrets validation check has failed. Please review the secrets configuration and address any issues.\n\nSee the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.',
              labels: ['security', 'secrets']
            })